language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.22.0
  - 1.23.0
  - 1.24.0

dist: trusty
sudo: false

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - texinfo
