language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.15.0
  - 1.20.0
  - 1.21.0

dist: trusty
sudo: false

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - texinfo
