pre-release-replacements = [
  { file="README.md", search="foropts = \"[0-9.]*\"", replace="foropts = \"{{version}}\"" },
  { file="src/lib.rs", search="foropts = \"[0-9.]*\"", replace="foropts = \"{{version}}\"" },
  { file="src/lib.rs", search="https://docs[.]rs/foropts/[0-9.]*", replace="https://docs.rs/foropts/{{version}}" }
]
